module.exports = {
  version: '0.0.0',
  license: 'MIT',
  main: 'dist/index.js',
  module: 'dist/index.es.js',
  'jsnext:main': 'dist/index.es.js',
  files: ['dist'],
  engines: {
    node: '>=8',
    npm: '>=5',
  },
  scripts: {
    build: 'rollup -c',
    start: 'rollup -c -w',
    prepare: 'yarn run build',
    lint: 'eslint .',
  },
  peerDependencies: {
    'prop-types': '^15.7.2',
    react: '^16.8.0',
    'react-dom': '^16.8.0',
  },
  devDependencies: {
    '@babel/cli': '^7.5.5',
    '@babel/core': '^7.5.5',
    '@babel/plugin-proposal-class-properties': '^7.5.5',
    '@babel/preset-env': '^7.5.5',
    '@babel/preset-react': '^7.0.0',
    '@svgr/rollup': '^4.3.2',
    'babel-eslint': '^10.0.2',
    'cross-env': '^5.2.0',
    eslint: '^6.1.0',
    'eslint-plugin-react': '^7.14.3',
    react: '^16.8.6',
    'react-dom': '^16.8.6',
    rollup: '^1.19.4',
    'rollup-plugin-babel': '^4.3.3',
    'rollup-plugin-commonjs': '^10.0.2',
    'rollup-plugin-node-resolve': '^5.0.4',
    'rollup-plugin-peer-deps-external': '^2.2.0',
    'rollup-plugin-postcss': '^2.0.3',
    'rollup-plugin-url': '^2.2.2',
  },
};
