module.exports = {
  version: '0.0.0',
  license: 'MIT',
  main: 'dist/index.js',
  module: 'dist/index.es.js',
  'jsnext:main': 'dist/index.es.js',
  files: ['dist'],
  engines: {
    node: '>=8',
    npm: '>=5',
  },
  scripts: {
    build: 'rollup -c',
    start: 'rollup -c -w',
    prepare: 'yarn run build',
    lint: 'eslint .',
  },
  peerDependencies: {
    'prop-types': '^15.7.2',
    react: '^16.13.1',
    'react-dom': '^16.13.1',
  },
  devDependencies: {
    '@babel/cli': '^7.8.4',
    '@babel/core': '^7.9.0',
    '@babel/plugin-proposal-class-properties': '^7.8.3',
    '@babel/preset-env': '^7.9.5',
    '@babel/preset-react': '^7.9.4',
    '@svgr/rollup': '^5.3.1',
    'babel-eslint': '^10.1.0',
    'cross-env': '^7.0.2',
    eslint: '^6.8.0',
    'eslint-plugin-react': '^7.19.0',
    react: '^16.13.1',
    'react-dom': '^16.13.1',
    rollup: '^2.6.0',
    'rollup-plugin-babel': '^4.4.0',
    'rollup-plugin-commonjs': '^10.1.0',
    'rollup-plugin-node-resolve': '^5.2.0',
    'rollup-plugin-peer-deps-external': '^2.2.2',
    'rollup-plugin-postcss': '^2.5.0',
    'rollup-plugin-url': '^3.0.1',
  },
};
